# **Clasificación de imágenes de quemaduras de segundo y tercer grado**

## Red Neuronal Convolucional

In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
from keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

## Blue

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        blue = resized_img[:, :, 0]

        X.append(blue)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

X = X[..., np.newaxis]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 1)
Shape of X_test: (45, 960, 540, 1)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 1)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 390ms/step - accuracy: 0.5519 - loss: 3.1114
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 332ms/step - accuracy: 0.4422 - loss: 1.0811
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 318ms/step - accuracy: 0.5788 - loss: 0.7280
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 326ms/step - accuracy: 0.5848 - loss: 0.6887
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.7309 - loss: 0.6214
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 321ms/step - accuracy: 0.6914 - loss: 0.6117
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.7038 - loss: 0.5810
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 326ms/step - accuracy: 0.8139 - loss: 0.4963
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 336ms/step - accuracy: 0.7934 - loss: 0.4726
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 328ms/step - accuracy: 0.8386 - loss: 0.4355
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 319ms/step - accuracy: 0.7472 - loss: 0.5447
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 331ms/step - accuracy: 0.7290 - lo

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 128ms/step
Matriz de confusión train:
 [[83  0]
 [ 0 97]]
Accuracy: 1.0
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

Matriz de confusión test:
 [[27  1]
 [ 6 11]]
Accuracy: 0.8444444444444444
Precision: 0.9166666666666666
Recall: 0.6470588235294118
F1 Score: 0.7586206896551724


## Green

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        green = resized_img[:, :, 1]

        X.append(green)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

X = X[..., np.newaxis]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 1)
Shape of X_test: (45, 960, 540, 1)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 1)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 258ms/step - accuracy: 0.5527 - loss: 8.6764
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 242ms/step - accuracy: 0.5857 - loss: 1.9554
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 244ms/step - accuracy: 0.6245 - loss: 0.9272
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 245ms/step - accuracy: 0.5708 - loss: 0.8154
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 234ms/step - accuracy: 0.6822 - loss: 0.6258
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 241ms/step - accuracy: 0.6921 - loss: 0.5952
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 250ms/step - accuracy: 0.6663 - loss: 0.6009
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 243ms/step - accuracy: 0.6537 - loss: 0.5908
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 247ms/step - accuracy: 0.7276 - loss: 0.5293
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 229ms/step - accuracy: 0.7894 - loss: 0.5020
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 247ms/step - accuracy: 0.7856 - loss: 0.4748
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 255ms/step - accuracy: 0.8313 - lo

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step
Matriz de confusión train:
 [[83  0]
 [ 0 97]]
Accuracy: 1.0
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step 

Matriz de confusión test:
 [[26  2]
 [ 0 17]]
Accuracy: 0.9555555555555556
Precision: 0.8947368421052632
Recall: 1.0
F1 Score: 0.9444444444444444


In [ ]:
models.save_model(cnn, 'green_cnn.keras')

## Red

In [7]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        red = resized_img[:, :, 2]

        X.append(red)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

X = X[..., np.newaxis]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 1)
Shape of X_test: (45, 960, 540, 1)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [9]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 1)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 313ms/step - accuracy: 0.4983 - loss: 6.6333
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 272ms/step - accuracy: 0.6013 - loss: 0.7777
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 282ms/step - accuracy: 0.5247 - loss: 0.6705
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 308ms/step - accuracy: 0.6246 - loss: 0.6414
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - accuracy: 0.6480 - loss: 0.6455
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 282ms/step - accuracy: 0.6582 - loss: 0.6079
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 275ms/step - accuracy: 0.7991 - loss: 0.5519
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 282ms/step - accuracy: 0.7664 - loss: 0.5262
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - accuracy: 0.7318 - loss: 0.5376
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 270ms/step - accuracy: 0.7472 - loss: 0.5553
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 285ms/step - accuracy: 0.7146 - loss: 0.5384
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 277ms/step - accuracy: 0.8037 - lo

In [11]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step
Matriz de confusión train:
 [[74  9]
 [ 1 96]]
Accuracy: 0.9444444444444444
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step 

Matriz de confusión test:
 [[25  3]
 [ 0 17]]
Accuracy: 0.9333333333333333
Precision: 0.85
Recall: 1.0
F1 Score: 0.918918918918919


## Blue and Green

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        blue = resized_img[:, :, 0]
        green = resized_img[:, :, 1]
        blue_green = np.dstack((blue, green))

        X.append(blue_green)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 2)
Shape of X_test: (45, 960, 540, 2)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 2)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 354ms/step - accuracy: 0.5134 - loss: 12.6864
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 293ms/step - accuracy: 0.5486 - loss: 2.6331
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 261ms/step - accuracy: 0.4909 - loss: 1.3056
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 267ms/step - accuracy: 0.6504 - loss: 0.7048
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 250ms/step - accuracy: 0.6146 - loss: 0.7067
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 250ms/step - accuracy: 0.7067 - loss: 0.6382
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 312ms/step - accuracy: 0.7315 - loss: 0.6258
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 367ms/step - accuracy: 0.6706 - loss: 0.5976
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 286ms/step - accuracy: 0.7793 - loss: 0.5416
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - accuracy: 0.7936 - loss: 0.5079
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 275ms/step - accuracy: 0.7943 - loss: 0.4808
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - accuracy: 0.8143 - l

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step
Matriz de confusión train:
 [[83  0]
 [ 0 97]]
Accuracy: 1.0
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

Matriz de confusión test:
 [[28  0]
 [ 3 14]]
Accuracy: 0.9333333333333333
Precision: 1.0
Recall: 0.8235294117647058
F1 Score: 0.9032258064516129


## Blue and Red

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        blue = resized_img[:, :, 0]
        red = resized_img[:, :, 2]
        blue_red = np.dstack((blue, red))

        X.append(blue_red)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 2)
Shape of X_test: (45, 960, 540, 2)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 2)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - accuracy: 0.4753 - loss: 8.1244
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - accuracy: 0.5640 - loss: 1.5337
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 287ms/step - accuracy: 0.5792 - loss: 0.7558
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 294ms/step - accuracy: 0.5363 - loss: 0.7236
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - accuracy: 0.5398 - loss: 0.6945
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 286ms/step - accuracy: 0.5835 - loss: 0.6828
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 306ms/step - accuracy: 0.6608 - loss: 0.6556
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 278ms/step - accuracy: 0.6127 - loss: 0.6449
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 288ms/step - accuracy: 0.7035 - loss: 0.5962
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 256ms/step - accuracy: 0.6763 - loss: 0.5577
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 282ms/step - accuracy: 0.7502 - loss: 0.5139
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 264ms/step - accuracy: 0.6666 - lo

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step
Matriz de confusión train:
 [[83  0]
 [ 0 97]]
Accuracy: 1.0
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

Matriz de confusión test:
 [[27  1]
 [ 2 15]]
Accuracy: 0.9333333333333333
Precision: 0.9375
Recall: 0.8823529411764706
F1 Score: 0.9090909090909091


## Green and Red

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))
        green = resized_img[:, :, 1]
        red = resized_img[:, :, 2]
        green_red = np.dstack((green, red))

        X.append(green_red)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 2)
Shape of X_test: (45, 960, 540, 2)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 2)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 269ms/step - accuracy: 0.4946 - loss: 5.6599
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 293ms/step - accuracy: 0.5501 - loss: 1.2679
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - accuracy: 0.6151 - loss: 0.8009
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 287ms/step - accuracy: 0.6534 - loss: 0.6631
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 267ms/step - accuracy: 0.6134 - loss: 0.6439
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 274ms/step - accuracy: 0.6725 - loss: 0.6431
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 281ms/step - accuracy: 0.6383 - loss: 0.6047
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - accuracy: 0.7801 - loss: 0.5138
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 285ms/step - accuracy: 0.7985 - loss: 0.4824
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - accuracy: 0.8555 - loss: 0.4462
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 283ms/step - accuracy: 0.7749 - loss: 0.4416
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 264ms/step - accuracy: 0.7701 - lo

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 119ms/step
Matriz de confusión train:
 [[82  1]
 [ 0 97]]
Accuracy: 0.9944444444444445
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

Matriz de confusión test:
 [[25  3]
 [ 0 17]]
Accuracy: 0.9333333333333333
Precision: 0.85
Recall: 1.0
F1 Score: 0.918918918918919


## RGB

In [2]:
width = 540
height = 960
ruta_carpeta = 'quemaduras/'

X = []
y = []

for i in os.listdir(ruta_carpeta):
    for j in os.listdir(ruta_carpeta + i):
        img = cv2.imread(ruta_carpeta + i + '/' + j)
        resized_img = cv2.resize(img, (width, height))

        X.append(resized_img)

        if i == 'segundo_grado':
            y.append([0, 1]) 
        else:
            y.append([1, 0])

X = np.array(X)
y = np.array(y)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (180, 960, 540, 3)
Shape of X_test: (45, 960, 540, 3)
Shape of y_train: (180, 2)
Shape of y_test: (45, 2)


In [4]:
cnn = tf.keras.Sequential([
    layers.Conv2D(32, 3,3, input_shape=(width, height, 3)),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(32, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Conv2D(64, 3,3),
    layers.Activation('relu'),
    layers.MaxPooling2D(pool_size=(2,2)),

    layers.Flatten(),
    layers.Dense(64),
    layers.Activation('relu'),

    layers.Dropout(0.5),
    layers.Dense(2),
    layers.Activation('sigmoid')
])

c:\Users\yamil\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=60)

Epoch 1/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - accuracy: 0.5282 - loss: 6.4543
Epoch 2/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 306ms/step - accuracy: 0.5549 - loss: 1.4865
Epoch 3/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 316ms/step - accuracy: 0.5492 - loss: 0.9526
Epoch 4/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 314ms/step - accuracy: 0.7056 - loss: 0.6371
Epoch 5/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - accuracy: 0.6038 - loss: 0.6460
Epoch 6/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - accuracy: 0.6872 - loss: 0.6111
Epoch 7/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 283ms/step - accuracy: 0.6906 - loss: 0.5874
Epoch 8/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 302ms/step - accuracy: 0.7001 - loss: 0.5764
Epoch 9/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 287ms/step - accuracy: 0.7192 - loss: 0.5629
Epoch 10/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 291ms/step - accuracy: 0.7625 - loss: 0.4964
Epoch 11/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - accuracy: 0.7656 - loss: 0.4716
Epoch 12/60
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 292ms/step - accuracy: 0.8352 - lo

In [6]:
#Train
y_pred_train = cnn.predict(X_train)

y_train_binary = np.argmax(y_train, axis=1)
y_pred_train_binary = np.argmax(y_pred_train, axis=1)

CM_train = confusion_matrix(y_train_binary, y_pred_train_binary)
accuracy_train = accuracy_score(y_train_binary, y_pred_train_binary)

print("Matriz de confusión train:\n", CM_train)
print("Accuracy:", accuracy_train)

#Test
y_pred = cnn.predict(X_test)

y_test_binary = np.argmax(y_test, axis=1)
y_pred_binary = np.argmax(y_pred, axis=1)

CM = confusion_matrix(y_test_binary, y_pred_binary)

accuracy = accuracy_score(y_test_binary, y_pred_binary)
precision = precision_score(y_test_binary, y_pred_binary)
recall = recall_score(y_test_binary, y_pred_binary)
f1 = f1_score(y_test_binary, y_pred_binary)

print("\nMatriz de confusión test:\n", CM)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 143ms/step
Matriz de confusión train:
 [[82  1]
 [ 0 97]]
Accuracy: 0.9944444444444445
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

Matriz de confusión test:
 [[26  2]
 [ 2 15]]
Accuracy: 0.9111111111111111
Precision: 0.8823529411764706
Recall: 0.8823529411764706
F1 Score: 0.8823529411764706
